<a href="https://colab.research.google.com/github/AntoniXGaudi/Data_Analysis_1/blob/main/Assignment_01_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [ ]:
# YOUR CODE IS HERE
import numpy as np



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
# YOUR CODE IS HERE


my_list = [5, 10, 15, 20, 25]
my_array = np.array(my_list)
print(my_array)

[ 5 10 15 20 25]


### 3. Generate an array of 5x5 with zeros. 

In [ ]:
# YOUR CODE IS HERE

my_array = np.zeros((5, 5))
print(my_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 4. Generate an array of 4x4 with ones and assign data type as int.

In [ ]:
# YOUR CODmy_array = np.ones((4, 4), dtype=int)
my_array = np.ones((4, 4), dtype=int)
print(my_array)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


### 5. Make all the values of the array above with the value of 7.

In [ ]:
# YOUR CODE IS HERE

my_array = np.ones((4, 4), dtype=int) * 7
print(my_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### 6. Create the previous array above by full() method.

In [ ]:
# YOUR CODE IS HERE

my_array = np.full((4, 4), 7, dtype=int)
print(my_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [ ]:
# YOUR CODE IS HERE

my_array = np.arange(2, 17, 2)
print(my_array)

[ 2  4  6  8 10 12 14 16]


### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [ ]:
# YOUR CODE IS HERE

my_matrix = np.arange(0, 25).reshape((5, 5))
print(my_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [ ]:
# YOUR CODE IS HERE

my_matrix = np.linspace(0, 24, 25, dtype=int).reshape((5, 5))
print(my_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 10. Create randomly 5 numbers with numpy.

In [ ]:
# YOUR CODE IS HERE

my_array = np.random.rand(5)
print(my_array)

[0.59446294 0.32960923 0.20422079 0.6569863  0.50658397]


### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [ ]:
# YOUR CODE IS HERE

my_array = np.random.randn(5, 5)
print(my_array)

[[ 1.73860688 -1.24374733  2.0865622  -0.15982367 -2.83839838]
 [-0.07452997  0.17823589  1.17563742 -0.90967181  2.57473853]
 [ 0.2182115  -0.25987162 -0.77958918 -1.11286828 -0.51949134]
 [ 0.02437239 -1.52318112 -1.35796467 -2.07789893  0.48190588]
 [-0.53451002  0.35534269  0.21073061 -0.72303187 -1.40550393]]


### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
# YOUR CODE IS HERE

my_array = np.random.randint(20, 51, size=(3, 4))
print(my_array)

[[38 31 42 32]
 [37 48 25 44]
 [20 30 49 34]]


### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [ ]:
# YOUR CODE IS HERE

ranarr = np.random.rand(48)
shape6x8 = ranarr.reshape(6, 8)
print(shape6x8)
shape4x12 = ranarr.reshape(4,12)
print(shape4x12)
shape4x24 = ranarr.reshape(2,24)
print(shape4x24)

[[0.66641209 0.75746942 0.6614337  0.68857038 0.30798945 0.44660229
  0.01862146 0.44671524]
 [0.23318514 0.45542413 0.09695572 0.70223791 0.03261114 0.41083738
  0.53104282 0.55160407]
 [0.76913412 0.14302357 0.06879016 0.1321038  0.29293849 0.43983954
  0.06032687 0.08985395]
 [0.07019275 0.97078547 0.97833954 0.22825699 0.7841663  0.76030795
  0.36985627 0.11124849]
 [0.93263049 0.31601172 0.11468044 0.30636192 0.55119733 0.5984511
  0.9613821  0.87537778]
 [0.8757921  0.70332646 0.81076422 0.33487032 0.58600515 0.19477998
  0.35304657 0.89496786]]
[[0.66641209 0.75746942 0.6614337  0.68857038 0.30798945 0.44660229
  0.01862146 0.44671524 0.23318514 0.45542413 0.09695572 0.70223791]
 [0.03261114 0.41083738 0.53104282 0.55160407 0.76913412 0.14302357
  0.06879016 0.1321038  0.29293849 0.43983954 0.06032687 0.08985395]
 [0.07019275 0.97078547 0.97833954 0.22825699 0.7841663  0.76030795
  0.36985627 0.11124849 0.93263049 0.31601172 0.11468044 0.30636192]
 [0.55119733 0.5984511  0.96138

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

np.reshape(ranarr, (6,8))

array([[0.66641209, 0.75746942, 0.6614337 , 0.68857038, 0.30798945,
        0.44660229, 0.01862146, 0.44671524],
       [0.23318514, 0.45542413, 0.09695572, 0.70223791, 0.03261114,
        0.41083738, 0.53104282, 0.55160407],
       [0.76913412, 0.14302357, 0.06879016, 0.1321038 , 0.29293849,
        0.43983954, 0.06032687, 0.08985395],
       [0.07019275, 0.97078547, 0.97833954, 0.22825699, 0.7841663 ,
        0.76030795, 0.36985627, 0.11124849],
       [0.93263049, 0.31601172, 0.11468044, 0.30636192, 0.55119733,
        0.5984511 , 0.9613821 , 0.87537778],
       [0.8757921 , 0.70332646, 0.81076422, 0.33487032, 0.58600515,
        0.19477998, 0.35304657, 0.89496786]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(4, -1)

array([[0.66641209, 0.75746942, 0.6614337 , 0.68857038, 0.30798945,
        0.44660229, 0.01862146, 0.44671524, 0.23318514, 0.45542413,
        0.09695572, 0.70223791],
       [0.03261114, 0.41083738, 0.53104282, 0.55160407, 0.76913412,
        0.14302357, 0.06879016, 0.1321038 , 0.29293849, 0.43983954,
        0.06032687, 0.08985395],
       [0.07019275, 0.97078547, 0.97833954, 0.22825699, 0.7841663 ,
        0.76030795, 0.36985627, 0.11124849, 0.93263049, 0.31601172,
        0.11468044, 0.30636192],
       [0.55119733, 0.5984511 , 0.9613821 , 0.87537778, 0.8757921 ,
        0.70332646, 0.81076422, 0.33487032, 0.58600515, 0.19477998,
        0.35304657, 0.89496786]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(3, -1)

array([[0.66641209, 0.75746942, 0.6614337 , 0.68857038, 0.30798945,
        0.44660229, 0.01862146, 0.44671524, 0.23318514, 0.45542413,
        0.09695572, 0.70223791, 0.03261114, 0.41083738, 0.53104282,
        0.55160407],
       [0.76913412, 0.14302357, 0.06879016, 0.1321038 , 0.29293849,
        0.43983954, 0.06032687, 0.08985395, 0.07019275, 0.97078547,
        0.97833954, 0.22825699, 0.7841663 , 0.76030795, 0.36985627,
        0.11124849],
       [0.93263049, 0.31601172, 0.11468044, 0.30636192, 0.55119733,
        0.5984511 , 0.9613821 , 0.87537778, 0.8757921 , 0.70332646,
        0.81076422, 0.33487032, 0.58600515, 0.19477998, 0.35304657,
        0.89496786]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [ ]:
# YOUR CODE IS HERE 
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [ ]:
# YOUR CODE IS HERE 
center_elements = mat[1:3, 1:3]
print(center_elements)


[[ 6  7]
 [10 11]]


### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
# YOUR CODE IS HERE 
col1 = mat[:, 0]
print(col1)

[ 1  5  9 13]


### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
sol2 = mat[1,::2]
print(sol2)


[5 7]


### 17.Assign 77 to every cell in 3rd column.

In [ ]:
# YOUR CODE IS HERE 
mat[:, 2] = 77
print(mat)


[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]]


### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [ ]:
# YOUR CODE IS HERE 
mat[[1,3],[0,2]]


array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
# YOUR CODE IS HERE 
mat[1::2, 0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 


In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 
smaller_10 = mat[mat < 10]
print(smaller_10)


[1 2 4 5 6 8 9]


In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

bigger_12 = mat[mat > 12]
print(bigger_12)

[77 77 77 13 14 77 16]


In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 
# YOUR CODE IS HERE 

Total = smaller_10+bigger_12
print(Total)
sum(Total)

[78 79 81 18 20 85 25]


386

In [ ]:
smaller_10+bigger_12

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 

(smaller_10+bigger_12).std()


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

print(mat)
print("\n")
np.sum(mat[:, 1])



[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]]




32

In [ ]:
# LET US OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

print(mat)

[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]]


In [ ]:
# YOUR CODE IS HERE 
np.sum(mat[:, 1])


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(mat)

col3 = mat[:, 2] 

median = np.median(col3)
print(median)
mean = np.mean(col3)
print(mean)
std = np.std(col3)
print(std)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
9.0
9.0
4.47213595499958


In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

col3 = mat[:, 2] 
print(col3)

[ 3  7 11 15]


In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

row3 = mat[ 2 , : ] 
print(row3)

[ 9 10 11 12]


In [ ]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
median_col3 = np.median(col3)
print(f"Median of column 3 is {median_col3}")


median_row3 = np.median(row3)
print(f"Median of row 3 is {median_row3}")


Median of column 3 is 9.0
Median of row 3 is 10.5


In [ ]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

mean_col3 = np.mean(col3)
print(mean_col3)
mean_row3 = np.mean(row3)
print(mean_row3)

9.0
10.5


In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 
std_col3 = np.std(col3)
print(std_col3)

std_row3 = np.std(row3)
print(std)

4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [ ]:
# YOUR CODE IS HERE 
import pandas as pd

# sorry, this is as far as I got today, couldn't finish the Pandas part

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [ ]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 

df = pd.read_csv("Salaries.csv")

FileNotFoundError: ignored

In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 



Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 



### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 



### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________